### PR TITLE
adds tcp_ping plugin

### PR DESCRIPTION
**Pull request by wvandeun**
adds tcp_ping plugin
closes https://github.com/nornir-automation/nornir/issues/520

### CODE REVIEW

**Comment by dbarrosop** [comment]
Very nice!

**Review by dbarrosop — APPROVED** [review]

**Comment by dbarrosop** [comment]
Test seems to be failing though, looks like localhost:22  is open while you expected it to be closed (inventory sets the ip of the fake devices to localhost)

**Comment by wvandeun** [comment]
Interesting.

Ideally we would be able to reproduce this test "locally"
as well. Which is not the case right now, the container and my machine don't
listen on 22/tcp.

I can setup openssh (or something else) to have a local listening socket
in the container easily.

But it raises another question, I'm also looking into porting over the
command and remote_command tasks. For the testing of the remote_command task we would
need to have an openssh server.

Not sure if it is possible to do that with github runners. Not sure if
we can properly authenticate to the openssh server running on the
runner. (I'm not aware of the username/password and I seem to be unable
to create a ~/.ssh/authorized_keys file).

The only option I see is to run all of the tests in a container on the
runner, and spin up additional containers for each host defined in the
"inventory" (potentiall using your stupid_ssh_server).

But maybe I'm missing something here...

**Comment by dbarrosop** [comment]
Github actions supports docker-compose so we could potentially start a few linux containers with openssh and use them for testing. We used to do that actually:

https://github.com/nornir-automation/nornir/commit/45c30a715ef1e79a7ff82d76a315ff5451a7e575

**Comment by wvandeun** [comment]
Yep. I'll take a shot at it.

**Comment by dbarrosop** [comment]
A thousand apologies, i have no clue how I missed this PR for so long... Rebasing and merging. Sorry again for missing this :(

**Comment by wvandeun** [comment]
Awesome! No need to apologize :)

**Pull request merged**
